### PR TITLE
Add frontend module tests

### PR DESCRIPTION
**Pull request by samhh**

### CODE REVIEW

**Comment by sallaben** [comment]
what still needs review here? or can we close this?

**Comment by samhh** [comment]
It's one of my first forays into testing, so I'm looking for any feedback at all from anyone with testing experience before I merge.

**Comment by samhh** [comment]
Welp, nobody has come forward. Future feedback welcome :-)

**Comment by samhh** [comment]
Now that we're using Babel 7 upstream this appears to be blocked for the time being.

Potentially relevant: https://github.com/facebook/jest/pull/4557

**Pull request merged**
